# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.12.0'
  displayName: 'Install Node.js'

- script: |
    node --version
    npm install -g @angular/cli
    npm install
    echo Listing folders...
    dir '$(Build.ArtifactStagingDirectory)'
    dir '$(Agent.BuildDirectory)'
    ng build --prod
    dir '$(Build.ArtifactStagingDirectory)'
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: './dist/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'mathTrainingDrop'
    publishLocation: 'Container'